name: Build test pipeline

on:
  push:
    branches:
      - "feature/**"
      - "release/**"
      - "hotfix/**"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Setup maven directory
      run: mkdir $HOME/.mvn

    - name: create extentions xml
      run: echo -e '<extensions xmlns="http://maven.apache.org/EXTENSIONS/1.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"\n  xsi:schemaLocation="http://maven.apache.org/EXTENSIONS/1.0.0 http://maven.apache.org/xsd/core-extensions-1.0.0.xsd">\n    <extension>\n      <groupId>org.springframework.build</groupId>\n      <artifactId>aws-maven</artifactId>\n      <version>5.0.0.RELEASE</version>\n    </extension>\n</extensions>' > $HOME/.mvn/extensions.xml

    - name: Compile build
      run: |
        mvn compile
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
