name: Petclinic CI pipeline

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Setup jdk 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with maven
        run: mvn --settings infra/maven_settings/settings.xml --file pom.xml package -Diam-user-access-key-id=${{ secrets.AWS_ACCESS_KEY_ID }} -Diam-user-secret-key=${{ secrets.AWS_ACCESS_KEY }}
      - name: list files
        run: ls -lart
